language: node_js
node_js:
- stable
- '7'
- '6'
- '5'
script:
- npm run bootstrap
- npm test
before_deploy: cd packages/visual-stack-docs && npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI324CJP3XVNEJNJA
  secret_access_key:
    secure: XVBeDBrjIId6smPoWqv6O2lZ8l+BIQGwkDnNg4gaNKjcH4tfsGrT0JuyB6mT7jrbtPxagUx0eH+AI49qGbW5Apx608LqJLu6b0Y/UPneZKmWSrott2xownUoR+WGg+JYtumR6BU6ScT5ZfUv66+rgVZG0w52rULOzcwW8k4myiM701QhvrMMyB2rtFOylUTwxjSU0UxSsAptRSc/axeZylv2q5War31DhOreNABFsIN82IYxwWqFclPbY7wxllL9xS1OmI01tqE/8bMFCuZIkWcLN90zwC6c0ctnpbCpkoxABvwCRjgYF9Uggsk2TeFe/gNeyTJ0HN4WBIUtyHai+S/4NxOdsIqPQKdyPruU0ovprzG8tS58/gX9B6Fd0Bgp8rMUCA8iMvH7GcPu9/NqMX8UgBvbhARQwFEXu4AB+CYZNl40qyv2d32c8F+P90xCZYASvZ7lM1c+I+5QKoHrywU3NCuDZcEtt5FTEcG0sUfW2NOn3aKbBG+tkLWK5io/zU6NdE5gvFQXpbGs4rJ3Br5bcgW3jZlSZeSi3tXrbd+hZ7nVE78Wf9M4IwFwGuTf6f5MH5OX2DaKK84ytoYW2WC6xTIY4Z8K9FvJu6fQ40EhVYOhKnbtfSKSdUEAAQ/BbN09JqxdkthMjK0PMNiAAHaZLAriNXQZwSBOW8BvBpk=
  bucket: visual-stack
  local-dir: build
  acl: public_read
  on:
    repo: cjdev/visual-stack
    node: stable
    branch: master
