name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Run lerna bootstrap
        run: npm run bootstrap
      - name: Run tests
        run: npm test
      - name: Build visual-stack-docs
        run: cd packages/visual-stack-docs && npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: visual-stack-docs
          path: packages/visual-stack-docs/build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: visual-stack-docs
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy visual-stack-docs to S3
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync . s3://visual-stack-docs --delete --acl public-read
      - name: Deploy visual-stack-docs branch to S3
        if: github.ref != 'refs/heads/master'
        run: aws s3 sync . s3://${GITHUB_REF#refs/heads/}.visual-stack-docs --delete --acl public-read
